#!/bin/sh

set -e

case "$1" in
	install|upgrade)
		# create the monasca group
		if ! getent group monasca > /dev/null 2>&1
		then
			addgroup --system monasca >/dev/null || true
		fi

		# create the mon-thresh user to avoid running monasca Thresh as root
		if ! getent passwd mon-thresh > /dev/null 2>&1
		then
			adduser --quiet \
				--system \
				--home /var/lib/monasca/thresh \
				--no-create-home \
				--ingroup monasca \
				--shell /bin/false \
				mon-thresh || true
		fi

		if [ "$(id -gn mon-thresh)"  = "nogroup" ]
		then
			usermod -g monasca mon-thresh
		fi

		# create log directory
		mkdir -p /var/log/monasca/thresh

		# change the permissions on key directories
		chown mon-thresh:monasca -R /var/log/monasca/thresh
		;;
	configure)
	;;
	abort-upgrade)
	;;
	*)
		echo "preinst called with unknown argument  \`$1'" >&2
		exit 0
		;;
esac

exit 0
